name: Build and deploy
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/cog-creators/cog-browser
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Login to GitHub Container Registry
        if: github.repository_owner == 'cog-creators'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.repository_owner == 'cog-creators' }}
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    name: Deploy to index.discord.red
    needs: build
    environment: Deployment
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'cog-creators' }}
    steps:
      - name: Trigger deployment.
        run: >-
          curl -H "X-Token: ${{ secrets.WEBHOOK_DEPLOY_INDEX_TOKEN }}" "${{ secrets.WEBHOOK_DEPLOY_INDEX_URL }}"
